
SELECT
    YEAR,
    STATE,
    BENES_MA_CNT,
    BENE_AVG_AGE,
    BENE_DUAL_PCT,
    ER_VISITS_PER_1000_BENES,
    OP_VISITS_PER_1000_BENES
FROM ma_geo
WHERE YEAR = 2022
ORDER BY BENES_MA_CNT DESC
