
SELECT
    SUM(CASE WHEN YEAR IS NULL THEN 1 ELSE 0 END) AS missing_year,
    SUM(CASE WHEN STATE IS NULL THEN 1 ELSE 0 END) AS missing_state,
    SUM(CASE WHEN BENES_MA_CNT IS NULL THEN 1 ELSE 0 END) AS missing_ma_benes
FROM ma_geo
