
SELECT
    YEAR,
    COUNT(*) AS total_rows,
    SUM(CASE WHEN ER_VISITS_PER_1000_BENES IS NULL THEN 1 ELSE 0 END) AS missing_er_visits_per_1000,
    SUM(CASE WHEN OP_VISITS_PER_1000_BENES IS NULL THEN 1 ELSE 0 END) AS missing_op_visits_per_1000
FROM ma_geo
GROUP BY YEAR
ORDER BY YEAR
